<a href="https://colab.research.google.com/github/HarshaPriya03/PythonLearning/blob/main/Copy_of_Numpy_11_01_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**- **Numerical Python:**

Numpy is a python library used for numerical computation. It provides a powerful object called ndarray(N-dimensional Array) which allows us to store and process large amount of numeircal data efficiently.

# **Key Feature of Numpy:**

1. Fast and memory efficient

2. Suports multidimensional array.

3. Built in maths & data operations.

4. Numpy stores element of same Data type.

# **Problem With List:**

1. Python lists are flexible but slow.

2. You cannot perform thee maths directly on python lists.

In [ ]:
a=[1,2,3,4,5]
b=[6,7,8,9,10]

#Addition of a+b
a+b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
#Addition element wise
result=[]
for i in range(len(a)):
  result.append(a[i]+b[i])

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

a+b

array([ 7,  9, 11, 13, 15])

In [ ]:
result

[7, 9, 11, 13, 15]

In [ ]:
li=[1,2,3,4,5]
li*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
import sys

In [ ]:
li=[1,2,3,4,5]   #list
num_arr=np.array([1,2,3,4,5])  #numpy array

print('Size of First Element of List:',sys.getsizeof(li[0]))
print('Whole Numpy Array Size:',num_arr.nbytes)

Size of First Element of List: 28
Whole Numpy Array Size: 40


Mathematical & Numerical Operations Quickly:

List:Loops

Numpy:Built in Fucntions

In [ ]:
#Install Numpy
# !pip install numpy

In [ ]:
import numpy as np

In [ ]:
#Let's Create numpy array
arr=np.array([100,200,300,400,500])

In [ ]:
arr

array([100, 200, 300, 400, 500])

In [ ]:
arr=np.array([100,40.5,100.5,30.7,'Siddharth'])

In [ ]:
arr

array(['100', '40.5', '100.5', '30.7', 'Siddharth'], dtype='<U32')

Priority List:

string>complex>float>int>bool

In [ ]:
arr=np.array([10,20,30,50.7,80.6,True])
print(arr)
print(arr.dtype) # dtype is used when you want to find the datatype of the array

[10.  20.  30.  50.7 80.6  1. ]
float64


In [ ]:
arr=np.array(['pragya',20,50,10,True,40.7,10.5])
print(arr)
print(arr.dtype)

['pragya' '20' '50' '10' 'True' '40.7' '10.5']
<U32


In [ ]:
# How we can get the dimension of the array
#ndim
arr=np.array([1,2,3,4,5,6])
print(arr)
print(arr.ndim)

[1 2 3 4 5 6]
1


In [ ]:
#How we can get the shape of the array
#shape
arr=np.array([1,2,3,4,5,6])
print(arr)
print(arr.shape)

[1 2 3 4 5 6]
(6,)


# 0-dimensional Array ( Single Value)

In [ ]:
zero_arr=np.array(30)
print(zero_arr)
print(zero_arr.ndim)
print(zero_arr.shape)

30
0
()


No of square brackets we use= Dimesion of the array

# **1-d Array-A line/Vector**

In [ ]:
arr=np.array([10,30,40,50,60])
print(arr)
print(arr.ndim)
print(arr.shape) #No of elements

[10 30 40 50 60]
1
(5,)


# **2-d Array-table/matrix**

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)
print(arr.shape)   #no of rows,no of columns

[[1 2 3]
 [4 5 6]]
2
(2, 3)


# **3-d-Array-a cube/stack of matrix-combination of 2d arrays**

In [ ]:
arr=np.array([[[20,40,10],[10,40,50]],[[10,40,20],[40,20,59]],[[10,50,20],[60,40,60]]])
print(arr)
print(arr.ndim)
print(arr.shape)  #how many 2d array used, no of rows in each 2d array, no of column in each 2 d array

[[[20 40 10]
  [10 40 50]]

 [[10 40 20]
  [40 20 59]]

 [[10 50 20]
  [60 40 60]]]
3
(3, 2, 3)


# **Array Indexing:**

In [ ]:
li=[10,50,80,40,70]
li

[10, 50, 80, 40, 70]

In [ ]:
li[2]

80

In [ ]:
li[0]

10

In [ ]:
# 1 d array
arr=np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [ ]:
# i want to get 40
print(arr[3])

40


In [ ]:
# i want to get 20
print(arr[1])

20


In [ ]:
#2 d array-
arr=np.array([[12,34,23],[10,20,30]])
arr

array([[12, 34, 23],
       [10, 20, 30]])

In [ ]:
# i want to get 20
print(arr[1,1])  #row index in which the element is present, the index of that particular element

20


In [ ]:
#i want to get 23
print(arr[0,2])

23


In [ ]:
#3d array
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[15,20,25]],[[100,200,300],[600,700,800]]])
print(arr)
#shape of array
print(arr.shape)

[[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 15  20  25]]

 [[100 200 300]
  [600 700 800]]]
(3, 2, 3)


In [ ]:
# i want to get 800
print(arr[2,1,2])  #in which 2d array my element is present, in which index row my element is present, the index of that particularr element

800


In [ ]:
#5
print(arr[0,1,1])

5


# **Array Slicing**

In [ ]:
#1 d array
arr=np.array([10,20,30,40,50,60,70])
arr

array([10, 20, 30, 40, 50, 60, 70])

In [ ]:
# i want to get the element from 20-60
print(arr[1:6])

[20 30 40 50 60]


In [ ]:
#2 d array
arr=np.array([[10,20,30],[40,50,60],[70,80,90],[100,110,120]])
arr

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [ ]:
#10 20 40 50
print(arr[0:2,0:2]) #slicing in row, slicing in the column

[[10 20]
 [40 50]]


In [ ]:
#70 80 90 100 110 120
print(arr[2:,:])

[[ 70  80  90]
 [100 110 120]]


In [ ]:
#10,20,30,70,80
print(arr[0:3:2,:])

[[10 20 30]
 [70 80 90]]


In [ ]:
#3d array
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[14,15,16]],[[17,18,19],[114,115,116]]])
arr

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 14,  15,  16]],

       [[ 17,  18,  19],
        [114, 115, 116]]])

In [ ]:
# i want to get  2 3 8 9 18 19
print(arr[:,0,1:])  #slicing in 2d block, slicing in rows, slcining in column

[[ 2  3]
 [ 8  9]
 [18 19]]


# **Convert dimensions of array from one to another**

In [ ]:
arr=np.array([10,20,30,40,50])
print(arr)
print(arr.ndim)

[10 20 30 40 50]
1


In [ ]:
# i want to conver this 1d array to 10d array
arr=np.array([10,20,30,40,50],ndmin=10)
print(arr)
print(arr.ndim)

[[[[[[[[[[10 20 30 40 50]]]]]]]]]]
10


In [ ]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]],ndmin=3)
print(arr)
print(arr.ndim)

[[[10 20 30]
  [40 50 60]
  [70 80 90]]]
3


In [ ]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[14,15,16]],[[17,18,19],[114,115,116]]],ndmin=2)
print(arr)
print(arr.ndim)

[[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 14  15  16]]

 [[ 17  18  19]
  [114 115 116]]]
3


In [ ]:
# i want to reduce the dimension from 3d to 2d
#ndmin does not reduce the dimensions

In [ ]:
#flatten()-This fxn is used to convert any dimension array to one dimension
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[14,15,16]],[[17,18,19],[114,115,116]]])
print(arr)
print(arr.ndim)

[[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 14  15  16]]

 [[ 17  18  19]
  [114 115 116]]]
3


In [ ]:
#3d->1d
arr1=arr.flatten()
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[  1   2   3   4   5   6   7   8   9  14  15  16  17  18  19 114 115 116]
1
(18,)


# **Reshape**

In [ ]:
#reshape()
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[14,15,16]],[[17,18,19],[114,115,116]]])
print(arr)
print(arr.shape)

[[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 14  15  16]]

 [[ 17  18  19]
  [114 115 116]]]
(3, 2, 3)


18--(9,2),(2,9)  , (3,6),(6,3)  ,(18,1),(1,18)

In [ ]:
# i want to convert this into 2d array
arr_2d=arr.reshape(3,6)

In [ ]:
print(arr_2d)
print(arr_2d.ndim)

[[  1   2   3   4   5   6]
 [  7   8   9  14  15  16]
 [ 17  18  19 114 115 116]]
2


# **Methods of creating arrays**

np.zeros()

np.ones()

np.full()

np.identity()

In [ ]:
#np.zeros()--> Create a numpy array with all the elements as 0
arr=np.zeros((3,3),dtype=int)

In [ ]:
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
#np.ones()-->Create a numpy array with all the elements as 1
arr=np.ones((4,6),dtype=int)
arr

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [ ]:
#np.full()-->Create a numpy array with a particular value
arr=np.full((3,4),10)
arr

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [ ]:
#np.identity()--> Create a  identity matrix
#Identity Matrix: It is a Square matrix in which all the diagonal elements is 1 and every other element will be 0
arr=np.identity(4,dtype=int)
arr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# **How to generate random numbers using numpy**

In [ ]:
#randint-It gives the random integers numbers between any range
#i want to create an array 25 random integer numbers between 50-100.
arr=np.random.randint(50,101,size=(4,5))
arr

array([[ 89,  60,  84,  58,  67],
       [ 81,  63, 100,  87,  85],
       [ 59,  98,  54,  92,  74],
       [ 51,  91,  62,  86,  73]])

In [ ]:
#rand-It gives you the random float values but between 0 and 1.
arr=np.random.rand(2,3,1)

In [ ]:
arr

array([[[0.50599103],
        [0.22238031],
        [0.66962637]],

       [[0.78095171],
        [0.8726624 ],
        [0.25031273]]])

In [ ]:
#uniform()-It gives the random float  values between any range
#i want to create an array with random float values between 50,100
arr=np.random.uniform(50,100,size=(2,3,5))

In [ ]:
arr

array([[[56.64576419, 90.03751245, 94.32332652, 65.42493479,
         80.55117897],
        [63.19840368, 96.25602473, 96.39713656, 70.285578  ,
         86.02870395],
        [84.19398335, 71.90732176, 64.65410015, 83.87754761,
         75.58856046]],

       [[97.1940231 , 75.3496874 , 99.94955852, 80.47715521,
         85.23876598],
        [82.73001669, 88.93896945, 96.70509923, 76.34482641,
         86.72109237],
        [98.80285794, 56.42001937, 76.75082691, 81.19642448,
         67.9854364 ]]])

# **How to find mean, median of values.**

In [ ]:
#Mean->Average
#data=[10,7,8,5,4]
#mena=sum of all the values/total no of values
     #=10+7+8+5+4/5
     #=34/5
     #=6.8
data=np.array([10,7,8,5,4])
avg=np.mean(data)

In [ ]:
avg

np.float64(6.8)

In [ ]:
#Median-Middly values of the valie
#data=[10,5,4,23,65,78,12,1]
#sort the data
#[1,4,5,10,12,23,65,78]
#look for the middle value
#even number of elements there will be 2 middly value
#mean of [10,12]
#medain=10+12/2
     #=22/2=11

In [ ]:
data=np.array([10,5,4,23,65,78,12,1])

In [ ]:
med=np.median(data)

In [ ]:
med

np.float64(11.0)

In [ ]:
# np.var(),np.std()

# **Mathematical Operations:**

In [ ]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

In [ ]:
#element wise addition
arr_sum=arr1+arr2
arr_sum

array([ 7,  9, 11, 13, 15])

In [ ]:
#consecutive elements sum
np.sum(arr1)

np.int64(15)

In [ ]:
np.sum(arr2)

np.int64(40)

In [ ]:
#subtraction element wise
arr_sub=arr1-arr2
arr_sub

array([-5, -5, -5, -5, -5])

In [ ]:
#consecutive elements subtraction
np.diff(arr1)

array([1, 1, 1, 1])

In [ ]:
np.diff(arr2)

array([1, 1, 1, 1])

In [ ]:
#multiplication element wise
arr_mul=arr1*arr2

In [ ]:
arr_mul

array([ 6, 14, 24, 36, 50])

In [ ]:
#consecutive element multiplication
np.prod(arr1)

np.int64(120)

In [ ]:
np.prod(arr2)

np.int64(30240)

In [ ]:
#concatenation
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr2

array([ 6,  7,  8,  9, 10])

In [ ]:
#concatenation-
concat_arr=np.concatenate((arr1,arr2))

In [ ]:
concat_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#vertical & horizontal stack
arr_v=np.vstack((arr1,arr2))

In [ ]:
arr_v

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr_h=np.hstack((arr1,arr2))
arr_h

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# **Linspace and Arange:**

Linspace:

Genrates evenly spaced numbers between start and stop including the endpoints.

linspace(start,end,num).

In [ ]:
arr=np.linspace(1,10,5).reshape(1,5)

In [ ]:
arr

array([[ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]])

Arange:

arange(start.stop,step)

It does not include the ending point.

In [ ]:
arr=np.arange(1,10,2)

In [ ]:
arr

array([1, 3, 5, 7, 9])

In [ ]:


# # **Assesment 1:**


# Tasks:


# 1. Create a Numpy array of numbers from 10 to 50 with step 5.


# 2. Convert the array to 2D array.


# 3. Extract first row and the last column from the array.


# 4. Replace all the values greater than 30 with -1.


# 5. Find : Mean, Max and Standard Deviation of the array.


# # **Assesment 2:**


# Tasks:


# You are given student marks:


# marks=np.array([45m78,62,90,55,38,84])


# 1. Find how many studnets scored above average.


# 2. Increase marks of student scoring below 50 by 5 points.


# 3. Sort the array in descending order.


# 4. Find the index of the highest score.

In [ ]:
import numpy as np

numbers=np.arange(10,51,5)
print(numbers)


[10 15 20 25 30 35 40 45 50]


In [ ]:
hi= numbers.reshape(3,3)
print(hi)

[[10 15 20]
 [25 30 35]
 [40 45 50]]


In [ ]:
# Assessment 1
# 1)     arr = np.arange(10, 51, 5)
# print("1. Original Array:", arr)
# 2)     arr_2d = arr.reshape(3, 3)
# print("2. 2D Array (3x3):\n", arr_2d)
# 3)     first_row = arr_2d[0, :]
# last_column = arr_2d[:, -1]
# print("3. First Row:", first_row)
# print(" Last Column:", last_column)
# 4)     arr_2d[arr_2d > 30] = -1
# print("4. Array after replacement:\n", arr_2d)
# 5)     print(f"5. Mean: {np.mean(arr_2d)}")
# print(f" Max: {np.max(arr_2d)}")
# print(f" Standard Deviation: {np.std(arr_2d):.2f}")


# Assessment 2
# marks = np.array([45, 78, 62, 90, 55, 38, 84])
# 1)     avg_marks = np.mean(marks)
# above_avg_count = np.sum(marks > avg_marks)
# print(f"1. Average: {avg_marks:.2f}. Students above average: {above_avg_count}")

# 2)     marks[marks < 50] += 5
# print("2. Marks after +5 adjustment:", marks)

# 3)     sorted_marks = np.sort(marks)[::-1]
# print("3. Sorted (Descending):", sorted_marks)

# 4)     highest_idx = np.argmax(marks)
# print(f"4. Index of highest score: {highest_idx} (Score: {marks[highest_idx]})")