<a href="https://colab.research.google.com/github/HarshaPriya03/PythonLearning/blob/main/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
vector = np.arange(5)

In [ ]:
print(vector)

[0 1 2 3 4]


In [ ]:
np.arange(24).reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
import pandas as pd
tips = pd.read_csv('tips.csv')

In [ ]:
tips.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [ ]:
tips.values # .values will convert a dataframe into a numpy array

array([[16.99, 1.01, 'Female', ..., 'Sun', 'Dinner', 2],
       [10.34, 1.66, 'Male', ..., 'Sun', 'Dinner', 3],
       [21.01, 3.5, 'Male', ..., 'Sun', 'Dinner', 3],
       ...,
       [22.67, 2.0, 'Male', ..., 'Sat', 'Dinner', 2],
       [17.82, 1.75, 'Male', ..., 'Sat', 'Dinner', 2],
       [18.78, 3.0, 'Female', ..., 'Thur', 'Dinner', 2]], dtype=object)

In [ ]:
mat1 = np.random.randint(10, 51, size = (3,3))
mat2 = np.random.randint(50, 100, size = (3,3))

In [ ]:
mat1

array([[12, 25, 47],
       [42, 47, 18],
       [13, 44, 46]])

In [ ]:
mat2

array([[72, 78, 63],
       [55, 59, 53],
       [94, 69, 69]])

In [ ]:
#addition of matrices
mat1 + mat2 #np.add(mat1, mat2)

array([[ 84, 103, 110],
       [ 97, 106,  71],
       [107, 113, 115]])

In [ ]:
mat1 + 10

array([[22, 35, 57],
       [52, 57, 28],
       [23, 54, 56]])

In [ ]:
#subtraction of matrices
mat1 - mat2

array([[-60, -53, -16],
       [-13, -12, -35],
       [-81, -25, -23]])

In [ ]:
mat2 - mat1

array([[60, 53, 16],
       [13, 12, 35],
       [81, 25, 23]])

In [ ]:
#division of matrices
mat1 / 10

array([[5. , 1.6, 1.4],
       [3.7, 4. , 2.3],
       [1.2, 1.3, 2.2]])

In [ ]:
mat1 / mat2

array([[0.19101124, 0.59210526, 0.45      ],
       [0.52272727, 0.45263158, 0.53448276],
       [0.1625    , 0.31395349, 0.33673469]])

In [ ]:
#element-wise multiplication or Hadamard product
mat1 * mat2

array([[4048, 2040, 1780],
       [1104,  864, 3402],
       [1320, 2006, 2574]])

In [ ]:
#actual matrix multiplication : Dot product
mat1 @ mat2 #np.dot(mat1, mat2)

array([[ 5272,  5578,  5487],
       [ 8574, 10025,  9185],
       [ 6173,  7399,  7551]])

In [ ]:
mat1

array([[12, 25, 47],
       [42, 47, 18],
       [13, 44, 46]])

In [ ]:
#transpose of a matrix
mat1.T

array([[12, 42, 13],
       [25, 47, 44],
       [47, 18, 46]])

In [ ]:
#matrix rank : helps us to identify duplicate or redundant data
np.linalg.matrix_rank(mat1)

np.int64(3)

In [ ]:
#determinant of a matrix : whether a matrix is singular or not
np.linalg.det(mat1)

np.float64(32128.99999999998)

In [ ]:
mat3 = np.arange(9).reshape(3,3)

In [ ]:
mat3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.linalg.det(mat3)

np.float64(0.0)

In [ ]:
np.linalg.inv(mat3)

LinAlgError: Singular matrix

In [ ]:
#inverse of a matrix
mat1_inv = np.linalg.inv(mat1)

In [ ]:
np.round((mat1_inv @ mat1), 2)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

In [ ]:
np.linalg.inv(mat3)

LinAlgError: Singular matrix

In [ ]:
matrix = np.array([[3, -2],
                   [1, 0]])

In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Original Matrix: ")
print(matrix)
print('\nEigenvalues: ')
print(eigenvalues)
print('\nEigenvectors: ')
print(eigenvectors)

Original Matrix: 
[[ 3 -2]
 [ 1  0]]

Eigenvalues: 
[2. 1.]

Eigenvectors: 
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [ ]:
np.dot(matrix, [0.89442719, 0.4472136])

array([1.78885437, 0.89442719])

In [ ]:
np.array([0.89442719, 0.4472136]) * 2

array([1.78885438, 0.8944272 ])