<a href="https://colab.research.google.com/github/HarshaPriya03/PythonLearning/blob/main/MLP_model_using_IRIS_from_Scratch_07June.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multiple Layer Perceptron Hands-on using `IRIS` dataset; building from scratch

![image.png](attachment:746d44bd-a7e6-4cd7-ac8d-17584e0cade4.png)

- `3 Categories / classes` 150 rows /instances equally distributed across 3 categories --> **Perfectly Balanced Dataset**

- 4 Features or Input Variables

- https://archive.ics.uci.edu/dataset/53/iris

#### `Accuracy` benchmarking across multiple models on `IRIS`

![image.png](attachment:1ba80661-34bc-4ab1-b90b-951b5448c8de.png)

#### `Precision` benchmarking across multiple models on `IRIS`

![image.png](attachment:21cdab1f-92b0-4092-af47-8b418ff9bead.png)

#### Import certain libraries

In [ ]:
import numpy as np
import pandas as pd
import os

import matplotlib.pyplot as plt
import seaborn as sns

##### To get the current working directory

In [ ]:
os.getcwd()

'C:\\Users\\ask2a\\OneDrive\\TRAINING\\INTELLIPAAT\\DEEP LEARNING\\13. AI and DL IITR-23May2026(E)'

In [ ]:
os.listdir()

['.ipynb_checkpoints',
 'Benchmarking Models across different use-cases_31May2026.ipynb',
 'Building ANN Models_31May.pdf',
 'Course Structure_23May.pdf',
 'customer_churn_dataset.csv',
 'Deep Learning Kick-Off Session_23May.pdf',
 'digit_data.csv',
 'fraud_detection_dataset.csv',
 'Industrial Applications or Use-cases_24May.pdf',
 'IRIS_24May.xlsx',
 'Let us build an App_24May.pdf',
 'loan_approval_dataset.csv',
 'MLP model using IRIS from Scratch_07June.ipynb',
 'mnist_train_31May.xlsx',
 'Module 1  Introduction to Deep Learning_23May.pdf',
 'Module 1  Introduction to Deep Learning_24May.pdf',
 'Module 2  Artificial Neural Networks (ANNs)_30May.pdf',
 'Module 2  Artificial Neural Networks (ANNs)_31May.pdf',
 'Multiple Layer Perceptron (MLP)_06June.pdf',
 'neural_network_playground_dataset.csv',
 'playground_viz.png',
 'Prompt Engineering_31May.pdf',
 'Setting up guidelines & expectations_23May.pdf',
 'Single Layer Perceptron (SLP) Model_06June.pdf',
 'Visualizing_Sample_Digit_7.ipynb

#### Load the `IRIS` data directly from `sklearn`

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
#### Loading the IRIS dataset
iris = load_iris() #iris object

In [ ]:
type(iris)

sklearn.utils._bunch.Bunch

- https://scikit-learn.org/stable/modules/generated/sklearn.utils.Bunch.html

In [ ]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
### Show the feature names for IRIS
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
iris_df = pd.DataFrame(data = iris['data'], columns=iris['feature_names'])
iris_df.sample(5)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
48,5.3,3.7,1.5,0.2
95,5.7,3.0,4.2,1.2
132,6.4,2.8,5.6,2.2
112,6.8,3.0,5.5,2.1
87,6.3,2.3,4.4,1.3


In [ ]:
### Let us add the `target` variable
iris_df['target'] = iris['target']
iris_df.sample(5)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
90,5.5,2.6,4.4,1.2,1
117,7.7,3.8,6.7,2.2,2
72,6.3,2.5,4.9,1.5,1
2,4.7,3.2,1.3,0.2,0
144,6.7,3.3,5.7,2.5,2


In [ ]:
iris['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### Let us convert `Label Encoding` to `One-Hot Encoding`

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
### Initialize the OneHotEncoder
encoder = OneHotEncoder(sparse_output= False)

In [ ]:
#### Reshape y to a 2D array (-1, 1) as required Sklearn
y_reshaped = iris.target.reshape(-1,1)
y_reshaped[:5] #2D-Array

array([[0],
       [0],
       [0],
       [0],
       [0]])

In [ ]:
iris.target[:5] #1-D Array

array([0, 0, 0, 0, 0])

In [ ]:
y_one_hot = encoder.fit_transform(y_reshaped)
y_one_hot

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

**TASK: Pls read about:**
- Label Encoding vs One-Hot Encoding
- What are different functions to OHE? - Try with Pandas - `pd.get_dummies`
- Build a `Random Forest` model for IRIS using LE as well as OHE & benchmark Accuracy & Precision and compare with UCI
- Revise OOPs principles