1. Import NumPy and Check the Version

In [33]:
import numpy as np
print(np.__version__)

1.24.3


2. Create a 1D Array
Create a 1D array of numbers from 0 to 9.

In [ ]:
import numpy as np
arr = np.arange(10)
print(arr)

3. Create a Boolean Array
Create a 3×3 numpy array of all True values.

In [1]:
import numpy as np

k = np.full((3,3), True)
print(k)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


4. Extract Items That Satisfy a Condition
Extract all odd numbers from arr

In [2]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
k = []
# Write your code below
for i in arr:
    if i%2 !=0:
        print(type(i))
        k.append(int(i))
print(k)

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
[1, 3, 5, 7, 9]


5. Replace Items That Satisfy a Condition
Replace all odd numbers in arr with -1

In [3]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
l = []
for i in arr:
    k= int(i)
    if k%2 != 0 :
        k = -1
        l.append(k)
    else:
        l.append(k)
print(l)

[0, -1, 2, -1, 4, -1, 6, -1, 8, -1]


6. Replace Items Without Affecting the Original Array
Replace all odd numbers in arr with -1 without modifying the original arr

In [4]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = arr.copy()
l = []
for i in out:
    k = int(i)
    if k % 2 != 0 :
        k = -1
        l.append(k)
    else:
        l.append(k)
l = np.array(l)
print(arr)
print(l)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


7. Reshape an Array
Convert the 1D array arr to a 2D array with 2 rows.

In [5]:
import numpy as np
arr = np.arange(10)
print(arr.reshape(2,-1))

[[0 1 2 3 4]
 [5 6 7 8 9]]


8. Stack Two Arrays Vertically
Stack arrays a and b vertically.

In [17]:
import numpy as np
arr = np.arange(10).reshape(2,-1)
# print(arr)
arr2 = np.repeat(1,10).reshape(2,-1)
# print(arr2)
print(np.concatenate([arr, arr2], axis=0))

# Method 2:
np.stack([arr, arr2])

# Method 3:
np.vstack([arr, arr2])

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

9. Stack Two Arrays Horizontally
Stack arrays a and b horizontally.

In [20]:
import numpy as np

arr = np.arange(10).reshape(2,-1)
arr2 = np.repeat(1,10).reshape(2,-1)

np.hstack([arr,arr2])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

10. Generate Custom Sequences Without Hardcoding
Using only numpy functions and the input array a, produce an array that first repeats each element 3 times, then tiles the whole array 3 times.

In [11]:
import numpy as np
a = np.array([1,2,3])
# for i in a:
#     k = np.repeat(i,3)
#     print(k)
l = np.repeat([1,2,3],3)
print(l)
l = np.tile([1,2,3],3)
print(l)
g = np.concatenate([np.repeat(i,3) for i in a])
print(g)

f= np.concatenate([np.repeat(i,3) for i in a], [np.tile([1,2,3],3)])
print(f)


[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3]


TypeError: 'list' object cannot be interpreted as an integer

In [ ]:
import numpy as np

a = np.array([1, 2, 3])

result = np.concatenate([np.repeat(a, 3), np.tile(a, 3)])
print(result)



#method 2:

import numpy as np

a = np.array([1, 2, 3])

result = np.r_[np.repeat(a, 3), np.tile(a, 3)]
print(result)


a = np.array([1,2,3])

result = np.concatenate([np.repeat(a,3), np.tile(a,3)])

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


11. Get Common Items Between Two Arrays
Find the common items between arrays a and b.

In [21]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

k = np.intersect1d(a,b)
print(k)


#three arrays 


a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])
c = np.array([3, 4, 5, 6])

k = np.intersect1d(np.intersect1d(a,b), c)
print(k)

[2 4]
[3 4]


12. Remove Items Present in Another Array
From array a, remove all items that are present in array b

In [27]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

k = np.setdiff1d(a,b)
print(k)


# l = a-b
# print(l)

[1 2 3 4]


13. Find Positions Where Two Arrays Match
Get the positions (indices) where elements of a and b are equal.

In [44]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(np.isin(a,b))[0])

[1 3 5 7]


14. Extract Numbers Within a Given Range
From array a, extract all items between 5 and 10 (inclusive).


In [45]:
import numpy as np
a = np.array([2, 6, 1, 9, 10, 3, 27])
result = a[(a >= 5) & (a <= 10)]
print(result)

[ 6  9 10]


15. Vectorize a Scalar Function to Work on Arrays
Convert the scalar function maxx into a vectorized version that works element-wise on arrays a and b.

In [ ]:
import numpy as np


def maxx(x,y):
    if x>=y:
        return x
    else:
        return y
par_maxx = np.vectorize(maxx, otypes = [float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

result = par_maxx(a,b)
print(result)


16. Swap Two Columns in a 2D Array
Swap columns 1 and 2 in the array arr.

In [4]:
import numpy as np
arr = np.arange(9).reshape(3,-1)
print(arr)

result = arr[:,[1,0,2]]
print(result)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


17. Swap Two Rows in a 2D Array
Swap rows 1 and 2 in the array arr.

In [6]:
import numpy as np
arr = np.arange(9).reshape(3,3)
result = arr[[1,0,2],:]
print(result)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


18. Reverse the Rows of a 2D Array
Reverse the row order of the 2D array arr.

In [7]:
import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr[::-1])

[[6 7 8]
 [3 4 5]
 [0 1 2]]


19. Reverse the Columns of a 2D Array
Reverse the column order of the 2D array arr

In [9]:
import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr[:,::-1])

[[2 1 0]
 [5 4 3]
 [8 7 6]]


20. Create a 2D Array of Random Floats Between 5 and 10
Create a 2D array of shape 5×3 containing random decimal numbers between 5 and 10.

In [11]:
arr = np.linspace(5,10,15).reshape(5,3)
print(arr)

[[ 5.          5.35714286  5.71428571]
 [ 6.07142857  6.42857143  6.78571429]
 [ 7.14285714  7.5         7.85714286]
 [ 8.21428571  8.57142857  8.92857143]
 [ 9.28571429  9.64285714 10.        ]]


21. Print Only 3 Decimal Places
Set NumPy print options so that the array rand_arr displays only 3 decimal places.

In [15]:
import numpy as np
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
print(rand_arr)

[[0.718 0.789 0.614]
 [0.324 0.291 0.836]
 [0.733 0.967 0.026]
 [0.474 0.131 0.273]
 [0.276 0.446 0.476]]


22. Suppress Scientific Notation in Print Output
Pretty print rand_arr by suppressing scientific notation (like 1e10).

In [17]:
import numpy as np
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
print(rand_arr)

[[5.434e-04 2.784e-04 4.245e-04]
 [8.448e-04 4.719e-06 1.216e-04]
 [6.707e-04 8.259e-04 1.367e-04]]


23. Limit the Number of Printed Items
Set NumPy print options so that array a displays a maximum of 6 elements, with the rest replaced by ellipsis.

In [19]:
import numpy as np
a = np.arange(9)
np.set_printoptions(threshold=6)
print(a)

[0 1 2 ... 6 7 8]


25. Import a Dataset With Mixed Types
Import the iris dataset from the URL, keeping the text (species) column intact alongside the numeric columns.

In [21]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
data = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
print(data[:3])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']]
