<a href="https://colab.research.google.com/github/HarshaPriya03/PythonLearning/blob/main/Numpy_Handson_17_01_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Create a numpy array from array numpy array module with a datatype float and integer.**

In [ ]:
import numpy as np

In [ ]:
arr_int=np.array([1,2,6.7,3.9,10.5],dtype=int)
print(arr_int)
print(arr_int.dtype)

[ 1  2  6  3 10]
int64


In [ ]:
arr_float=(np.array([9,20,10.7,30,20.8],dtype=float))
print(arr_float)
print(arr_float.dtype)

[ 9.  20.  10.7 30.  20.8]
float64


**Create numpy arrays which have zero,one,two,three dimesnion.Also print the shape and dimension of the numpy array.**

In [ ]:
#0d array
arr=np.array(30)
print(arr)
print('Shape:',arr.shape)
print('Dimension',arr.ndim)

30
Shape: ()
Dimension 0


In [ ]:
#1d array
arr=np.array([1,2,3,4,5])
print(arr)
print('Shape',arr.shape)
print('Diemshion:',arr.ndim)

[1 2 3 4 5]
Shape (5,)
Diemshion: 1


In [ ]:
#2d array
arr=np.array([[1,2,3],[4,5,6],[8,9,10],[111,112,113]])
print(arr)
print('Shape',arr.shape)
print('Dimension',arr.ndim)

[[  1   2   3]
 [  4   5   6]
 [  8   9  10]
 [111 112 113]]
Shape (4, 3)
Dimension 2


In [ ]:
#3d array
arr=np.array([[[1,2,3],[4,5,6]],[[9,10,10],[20,11,19]],[[17,18,19],[20,21,222]]])
print(arr)
print('Shape:',arr.shape)
print('Dimension:',arr.ndim)

[[[  1   2   3]
  [  4   5   6]]

 [[  9  10  10]
  [ 20  11  19]]

 [[ 17  18  19]
  [ 20  21 222]]]
Shape: (3, 2, 3)
Dimension: 3


**Create a 3x3 ,4x4 and 2x3 Identity Matrix using Numpy?**

In [ ]:
arr=np.identity(3,dtype=int)
print(arr)
print(arr.shape)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
(3, 3)


In [ ]:
arr=np.identity(4,dtype=int)
print(arr)
print(arr.shape)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
(4, 4)


In [ ]:
arr=np.eye(2,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]]


**Create a numpy array with shape 2x5 that has all the elements as zero.**

In [ ]:
arr=np.zeros((2,5),dtype=int)

In [ ]:
print(arr)
arr.shape

[[0 0 0 0 0]
 [0 0 0 0 0]]


(2, 5)

In [ ]:
arr=np.full((2,5),0)
print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]]


Create a numpy array tha has the size 3x5 and all the elements should be 5.

In [ ]:
# Homework

**Create a Numpy array with random integeres in the range 0-100 and the size should be 25.**

In [ ]:
arr=np.random.randint(0,101,25)

In [ ]:
arr

array([45, 83, 13, 13, 87, 26, 54, 62,  5, 58, 85,  7, 79,  6, 22, 58, 67,
       97, 59,  9, 97, 13, 79, 74, 65])

Create a numpy array in the shape 2*3 with random integers in the range 0-100.Reshape this arry in the shape 3*2 and print the updated shape of the resultant array.

In [ ]:
arr=np.random.randint(0,101,size=(2,3))
print(arr)
print(arr.shape)

[[23 51 54]
 [65  9 40]]
(2, 3)


In [ ]:
reshape_arr=arr.reshape(3,2)
print(reshape_arr)
print(reshape_arr.shape)

[[23 51]
 [54 65]
 [ 9 40]]
(3, 2)


Create a random array with integer value between 0-1000 with a size of 50 and Perform the following Operation:

a. Print the first ten element of the array.

b. Print the last ten element of the array.

c. Print the element from the indec 10-25.

d.Print the element present at index 22.

In [ ]:
arr=np.random.randint(0,1000,size=50)

In [ ]:
arr

array([991, 572, 185, 229, 907, 381, 501, 352,  85, 117, 404, 200, 633,
       591, 746, 355,  52, 414, 832, 672, 163, 639, 471, 974, 872, 279,
       153, 112, 866, 444, 924, 707, 603, 464,  56, 890, 647, 284, 507,
       103, 131, 807, 292, 838, 804, 359,  27, 967, 329, 916])

In [ ]:
#a. Print the first ten element of the array.
print(arr[:10])

[991 572 185 229 907 381 501 352  85 117]


In [ ]:
#b. Print the last ten element of the array.
print(arr[40:])

[131 807 292 838 804 359  27 967 329 916]


In [ ]:
#c. Print the element from the indec 10-25.
print(arr[10:26])

[404 200 633 591 746 355  52 414 832 672 163 639 471 974 872 279]


In [ ]:
#d.Print the element present at index 22.
print(arr[22])

471


Given a Numpy that has the values arr=[1,2,3,4,5].Perform the following operations:

a.Insert the elemnt 6 at the end of the array.

b. Insert the element 10 at the beginning of the array.

c.Insert 30 before 4.

d. Deletee the element 30.

In [ ]:
arr=np.array([1,2,3,4,5])

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
#a.Insert the elemnt 6 at the end of the array.
arr=np.append(arr,6)

In [ ]:
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
#b. Insert the element 10 at the beginning of the array.
arr=np.insert(arr,0,10)

In [ ]:
arr

array([10,  1,  2,  3,  4,  5,  6])

In [ ]:
#c.Insert 30 before 4.
arr=np.insert(arr,4,30)

In [ ]:
arr

array([10,  1,  2,  3, 30,  4,  5,  6])

In [ ]:
#d. Deletee the element 30.
arr=np.delete(arr,4)

In [ ]:
arr

array([10,  1,  2,  3,  4,  5,  6])

# **Assesment 1:**

Tasks:

1. Create a Numpy array of numbers from 10 to 50 with step 5.

2. Convert the array to 2D array.

3. Extract first row and the last column from the array.

4. Replace all the values greater than 30 with -1.

5. Find : Mean, Max and Standard Deviation of the array.

# **Assesment 2:**

Tasks:

You are given student marks:

marks=np.array([45m78,62,90,55,38,84])

1. Find how many studnets scored above average.

2. Increase marks of student scoring below 50 by 5 points.

3. Sort the array in descending order.

4. Find the index of the highest score.

