1. Import NumPy and Check the Version

In [ ]:
import numpy as np
print(np.__version__)

2. Create a 1D Array
Create a 1D array of numbers from 0 to 9.

In [ ]:
import numpy as np
arr = np.arange(10)
print(arr)

3. Create a Boolean Array
Create a 3×3 numpy array of all True values.

In [1]:
import numpy as np

k = np.full((3,3), True)
print(k)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


4. Extract Items That Satisfy a Condition
Extract all odd numbers from arr

In [2]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
k = []
# Write your code below
for i in arr:
    if i%2 !=0:
        print(type(i))
        k.append(int(i))
print(k)

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
[1, 3, 5, 7, 9]


5. Replace Items That Satisfy a Condition
Replace all odd numbers in arr with -1

In [3]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
l = []
for i in arr:
    k= int(i)
    if k%2 != 0 :
        k = -1
        l.append(k)
    else:
        l.append(k)
print(l)

[0, -1, 2, -1, 4, -1, 6, -1, 8, -1]


6. Replace Items Without Affecting the Original Array
Replace all odd numbers in arr with -1 without modifying the original arr

In [4]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = arr.copy()
l = []
for i in out:
    k = int(i)
    if k % 2 != 0 :
        k = -1
        l.append(k)
    else:
        l.append(k)
l = np.array(l)
print(arr)
print(l)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


7. Reshape an Array
Convert the 1D array arr to a 2D array with 2 rows.

In [5]:
import numpy as np
arr = np.arange(10)
print(arr.reshape(2,-1))

[[0 1 2 3 4]
 [5 6 7 8 9]]


8. Stack Two Arrays Vertically
Stack arrays a and b vertically.

In [17]:
import numpy as np
arr = np.arange(10).reshape(2,-1)
# print(arr)
arr2 = np.repeat(1,10).reshape(2,-1)
# print(arr2)
print(np.concatenate([arr, arr2], axis=0))

# Method 2:
np.stack([arr, arr2])

# Method 3:
np.vstack([arr, arr2])

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

9. Stack Two Arrays Horizontally
Stack arrays a and b horizontally.

In [20]:
import numpy as np

arr = np.arange(10).reshape(2,-1)
arr2 = np.repeat(1,10).reshape(2,-1)

np.hstack([arr,arr2])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

10. Generate Custom Sequences Without Hardcoding
Using only numpy functions and the input array a, produce an array that first repeats each element 3 times, then tiles the whole array 3 times.

In [ ]:
import numpy as np
a = np.array([1,2,3])
