1. Import NumPy and Check the Version

In [33]:
import numpy as np
print(np.__version__)

1.24.3


2. Create a 1D Array
Create a 1D array of numbers from 0 to 9.

In [ ]:
import numpy as np
arr = np.arange(10)
print(arr)

3. Create a Boolean Array
Create a 3×3 numpy array of all True values.

In [1]:
import numpy as np

k = np.full((3,3), True)
print(k)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


4. Extract Items That Satisfy a Condition
Extract all odd numbers from arr

In [2]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
k = []
# Write your code below
for i in arr:
    if i%2 !=0:
        print(type(i))
        k.append(int(i))
print(k)

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
[1, 3, 5, 7, 9]


5. Replace Items That Satisfy a Condition
Replace all odd numbers in arr with -1

In [3]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
l = []
for i in arr:
    k= int(i)
    if k%2 != 0 :
        k = -1
        l.append(k)
    else:
        l.append(k)
print(l)

[0, -1, 2, -1, 4, -1, 6, -1, 8, -1]


6. Replace Items Without Affecting the Original Array
Replace all odd numbers in arr with -1 without modifying the original arr

In [4]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = arr.copy()
l = []
for i in out:
    k = int(i)
    if k % 2 != 0 :
        k = -1
        l.append(k)
    else:
        l.append(k)
l = np.array(l)
print(arr)
print(l)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


7. Reshape an Array
Convert the 1D array arr to a 2D array with 2 rows.

In [5]:
import numpy as np
arr = np.arange(10)
print(arr.reshape(2,-1))

[[0 1 2 3 4]
 [5 6 7 8 9]]


8. Stack Two Arrays Vertically
Stack arrays a and b vertically.

In [17]:
import numpy as np
arr = np.arange(10).reshape(2,-1)
# print(arr)
arr2 = np.repeat(1,10).reshape(2,-1)
# print(arr2)
print(np.concatenate([arr, arr2], axis=0))

# Method 2:
np.stack([arr, arr2])

# Method 3:
np.vstack([arr, arr2])

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

9. Stack Two Arrays Horizontally
Stack arrays a and b horizontally.

In [20]:
import numpy as np

arr = np.arange(10).reshape(2,-1)
arr2 = np.repeat(1,10).reshape(2,-1)

np.hstack([arr,arr2])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

10. Generate Custom Sequences Without Hardcoding
Using only numpy functions and the input array a, produce an array that first repeats each element 3 times, then tiles the whole array 3 times.

In [11]:
import numpy as np
a = np.array([1,2,3])
# for i in a:
#     k = np.repeat(i,3)
#     print(k)
l = np.repeat([1,2,3],3)
print(l)
l = np.tile([1,2,3],3)
print(l)
g = np.concatenate([np.repeat(i,3) for i in a])
print(g)

f= np.concatenate([np.repeat(i,3) for i in a], [np.tile([1,2,3],3)])
print(f)


[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3]


TypeError: 'list' object cannot be interpreted as an integer

In [ ]:
import numpy as np

a = np.array([1, 2, 3])

result = np.concatenate([np.repeat(a, 3), np.tile(a, 3)])
print(result)



#method 2:

import numpy as np

a = np.array([1, 2, 3])

result = np.r_[np.repeat(a, 3), np.tile(a, 3)]
print(result)


a = np.array([1,2,3])

result = np.concatenate([np.repeat(a,3), np.tile(a,3)])

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


11. Get Common Items Between Two Arrays
Find the common items between arrays a and b.

In [21]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

k = np.intersect1d(a,b)
print(k)


#three arrays 


a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])
c = np.array([3, 4, 5, 6])

k = np.intersect1d(np.intersect1d(a,b), c)
print(k)

[2 4]
[3 4]


12. Remove Items Present in Another Array
From array a, remove all items that are present in array b

In [27]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

k = np.setdiff1d(a,b)
print(k)


# l = a-b
# print(l)

[1 2 3 4]


13. Find Positions Where Two Arrays Match
Get the positions (indices) where elements of a and b are equal.

In [44]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(np.isin(a,b))[0])

[1 3 5 7]


14. Extract Numbers Within a Given Range
From array a, extract all items between 5 and 10 (inclusive).


In [45]:
import numpy as np
a = np.array([2, 6, 1, 9, 10, 3, 27])
result = a[(a >= 5) & (a <= 10)]
print(result)

[ 6  9 10]


15. Vectorize a Scalar Function to Work on Arrays
Convert the scalar function maxx into a vectorized version that works element-wise on arrays a and b.

In [ ]:
import numpy as np
