<a href="https://colab.research.google.com/github/HarshaPriya03/PythonLearning/blob/main/Numpy_11_01_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**- **Numerical Python:**

Numpy is a python library used for numerical computation. It provides a powerful object called ndarray(N-dimensional Array) which allows us to store and process large amount of numeircal data efficiently.

# **Key Feature of Numpy:**

1. Fast and memory efficient

2. Suports multidimensional array.

3. Built in maths & data operations.

4. Numpy stores element of same Data type.

# **Problem With List:**

1. Python lists are flexible but slow.

2. You cannot perform thee maths directly on python lists.

In [ ]:
a=[1,2,3,4,5]
b=[6,7,8,9,10]

#Addition of a+b
a+b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
#Addition element wise
result=[]
for i in range(len(a)):
  result.append(a[i]+b[i])

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

a+b

array([ 7,  9, 11, 13, 15])

In [ ]:
result

[7, 9, 11, 13, 15]

In [ ]:
li=[1,2,3,4,5]
li*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
import sys

In [ ]:
li=[1,2,3,4,5]   #list
num_arr=np.array([1,2,3,4,5])  #numpy array

print('Size of First Element of List:',sys.getsizeof(li[0]))
print('Whole Numpy Array Size:',num_arr.nbytes)

Size of First Element of List: 28
Whole Numpy Array Size: 40


Mathematical & Numerical Operations Quickly:

List:Loops

Numpy:Built in Fucntions

In [ ]:
#Install Numpy
# !pip install numpy

In [ ]:
import numpy as np

In [ ]:
#Let's Create numpy array
arr=np.array([100,200,300,400,500])

In [ ]:
arr

array([100, 200, 300, 400, 500])

In [ ]:
arr=np.array([100,40.5,100.5,30.7,'Siddharth'])

In [ ]:
arr

array(['100', '40.5', '100.5', '30.7', 'Siddharth'], dtype='<U32')

Priority List:

string>complex>float>int>bool

In [ ]:
arr=np.array([10,20,30,50.7,80.6,True])
print(arr)
print(arr.dtype) # dtype is used when you want to find the datatype of the array

[10.  20.  30.  50.7 80.6  1. ]
float64


In [ ]:
arr=np.array(['pragya',20,50,10,True,40.7,10.5])
print(arr)
print(arr.dtype)

['pragya' '20' '50' '10' 'True' '40.7' '10.5']
<U32


In [ ]:
# How we can get the dimension of the array
#ndim
arr=np.array([1,2,3,4,5,6])
print(arr)
print(arr.ndim)

[1 2 3 4 5 6]
1


In [ ]:
#How we can get the shape of the array
#shape
arr=np.array([1,2,3,4,5,6])
print(arr)
print(arr.shape)

[1 2 3 4 5 6]
(6,)


# 0-dimensional Array ( Single Value)

In [ ]:
zero_arr=np.array(30)
print(zero_arr)
print(zero_arr.ndim)
print(zero_arr.shape)

30
0
()


No of square brackets we use= Dimesion of the array

# **1-d Array-A line/Vector**

In [ ]:
arr=np.array([10,30,40,50,60])
print(arr)
print(arr.ndim)
print(arr.shape) #No of elements

[10 30 40 50 60]
1
(5,)


# **2-d Array-table/matrix**

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)
print(arr.shape)   #no of rows,no of columns

[[1 2 3]
 [4 5 6]]
2
(2, 3)


# **3-d-Array-a cube/stack of matrix-combination of 2d arrays**

In [ ]:
arr=np.array([[[20,40,10],[10,40,50]],[[10,40,20],[40,20,59]],[[10,50,20],[60,40,60]]])
print(arr)
print(arr.ndim)
print(arr.shape)  #how many 2d array used, no of rows in each 2d array, no of column in each 2 d array

[[[20 40 10]
  [10 40 50]]

 [[10 40 20]
  [40 20 59]]

 [[10 50 20]
  [60 40 60]]]
3
(3, 2, 3)


# **Array Indexing:**

In [ ]:
li=[10,50,80,40,70]
li

[10, 50, 80, 40, 70]

In [ ]:
li[2]

80

In [ ]:
li[0]

10

In [ ]:
# 1 d array
arr=np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [ ]:
# i want to get 40
print(arr[3])

40


In [ ]:
# i want to get 20
print(arr[1])

20


In [ ]:
#2 d array-
arr=np.array([[12,34,23],[10,20,30]])
arr

array([[12, 34, 23],
       [10, 20, 30]])

In [ ]:
# i want to get 20
print(arr[1,1])  #row index in which the element is present, the index of that particular element

20


In [ ]:
#i want to get 23
print(arr[0,2])

23


In [ ]:
#3d array
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[15,20,25]],[[100,200,300],[600,700,800]]])
print(arr)
#shape of array
print(arr.shape)

[[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 15  20  25]]

 [[100 200 300]
  [600 700 800]]]
(3, 2, 3)


In [ ]:
# i want to get 800
print(arr[2,1,2])  #in which 2d array my element is present, in which index row my element is present, the index of that particularr element

800


In [ ]:
#5
print(arr[0,1,1])

5


# **Array Slicing**

In [ ]:
#1 d array
arr=np.array([10,20,30,40,50,60,70])
arr

array([10, 20, 30, 40, 50, 60, 70])

In [ ]:
# i want to get the element from 20-60
print(arr[1:6])

[20 30 40 50 60]


In [ ]:
#2 d array
arr=np.array([[10,20,30],[40,50,60],[70,80,90],[100,110,120]])
arr

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [ ]:
#10 20 40 50
print(arr[0:2,0:2]) #slicing in row, slicing in the column

[[10 20]
 [40 50]]


In [ ]:
#70 80 90 100 110 120
print(arr[2:,:])

[[ 70  80  90]
 [100 110 120]]


In [ ]:
#10,20,30,70,80
print(arr[0:3:2,:])

[[10 20 30]
 [70 80 90]]


In [ ]:
#3d array
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[14,15,16]],[[17,18,19],[114,115,116]]])
arr

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 14,  15,  16]],

       [[ 17,  18,  19],
        [114, 115, 116]]])

In [ ]:
# i want to get  2 3 8 9 18 19
print(arr[:,0,1:])  #slicing in 2d block, slicing in rows, slcining in column

[[ 2  3]
 [ 8  9]
 [18 19]]


# **Convert dimensions of array from one to another**

In [ ]:
arr=np.array([10,20,30,40,50])
print(arr)
print(arr.ndim)

[10 20 30 40 50]
1


In [ ]:
# i want to conver this 1d array to 10d array
arr=np.array([10,20,30,40,50],ndmin=10)
print(arr)
print(arr.ndim)

[[[[[[[[[[10 20 30 40 50]]]]]]]]]]
10


In [ ]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]],ndmin=3)
print(arr)
print(arr.ndim)

[[[10 20 30]
  [40 50 60]
  [70 80 90]]]
3


In [ ]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[14,15,16]],[[17,18,19],[114,115,116]]],ndmin=2)
print(arr)
print(arr.ndim)

[[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 14  15  16]]

 [[ 17  18  19]
  [114 115 116]]]
3


In [ ]:
# i want to reduce the dimension from 3d to 2d
#ndmin does not reduce the dimensions

In [ ]:
#flatten()-This fxn is used to convert any dimension array to one dimension
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[14,15,16]],[[17,18,19],[114,115,116]]])
print(arr)
print(arr.ndim)

[[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 14  15  16]]

 [[ 17  18  19]
  [114 115 116]]]
3


In [ ]:
#3d->1d
arr1=arr.flatten()
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[  1   2   3   4   5   6   7   8   9  14  15  16  17  18  19 114 115 116]
1
(18,)


# **Reshape**

In [ ]:
#reshape()
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[14,15,16]],[[17,18,19],[114,115,116]]])
print(arr)
print(arr.shape)

[[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 14  15  16]]

 [[ 17  18  19]
  [114 115 116]]]
(3, 2, 3)


18--(9,2),(2,9)  , (3,6),(6,3)  ,(18,1),(1,18)

In [ ]:
# i want to convert this into 2d array
arr_2d=arr.reshape(3,6)

In [ ]:
print(arr_2d)
print(arr_2d.ndim)

[[  1   2   3   4   5   6]
 [  7   8   9  14  15  16]
 [ 17  18  19 114 115 116]]
2


# **Methods of creating arrays**

np.zeros()

np.ones()

np.full()

np.identity()

In [ ]:
#np.zeros()--> Create a numpy array with all the elements as 0
arr=np.zeros((3,3),dtype=int)

In [ ]:
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
#np.ones()-->Create a numpy array with all the elements as 1
arr=np.ones((4,6),dtype=int)
arr

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [ ]:
#np.full()-->Create a numpy array with a particular value
arr=np.full((3,4),10)
arr

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [ ]:
#np.identity()--> Create a  identity matrix
#Identity Matrix: It is a Square matrix in which all the diagonal elements is 1 and every other element will be 0
arr=np.identity(4,dtype=int)
arr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])